id: P892A4BF6
initial_creation_type: input
source_metadata:
  title: Songs and Poems Series
  language: pt
  description: 'A selection of spiritual songs (mgur; glu) or poems:'
  volume:
    0ff255f252df40efb521b7742895d038:
      title: Acrostic Song
      parent: Acrostic
    77810b667b7248429d348db69e1bc4bf:
      title: A Song for Travelling from Sikkim to Tibet
      parent: Advice
    a870becb7c05434c8c3ef03d4ed2b259:
      title: Advice to Myself Exposing Hidden Flaws
      parent: Advice
    8dfb35c2e07b452489e8fc6e01c93d8d:
      title: Khandro's Plea
      parent: Advice
    659e0ba59a284d1a8ce84b8ad5b8cd64:
      title: 'The Blissful Path to Awakening: A Song on the Essence of Definitive
        Meaning'
      parent: Advice
    c7081152ea8d45e5b2b14b07cc3064a0:
      title: How to Take the Practice to Heart
      parent: Advice
    1cdde564ade74bb9a3bab6311c80ac6d:
      title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
      parent: Advice
    7c0bdd1bec31443994dd4e882c48d5d3:
      title: Many Are the Scholars Who Travel Empty-Handed to the Realm of the Dead
      parent: Advice
    9f838da1451b4998ac079027e0f82c18:
      title: 'Divine Music: Words of Encouragement for the Authentic Path'
      parent: Advice
    b011cc67ac7e4d7c869d20799057b9e5:
      title: Song of the Enchanting Wildwoods
      parent: Advice
    81dd4154f2824b6687ffd99bc19c891d:
      title: A Song of Amazement Inspired by Practice Experience
      parent: Advice
    40c99969d6a346c7b1236ee6beafef63:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      parent: Advice
    289f6ce887b7486e8193e019ca5d965e:
      title: Types of Spiritual Song
      parent: Classification
    f1e606d0bf214adfbc975cbab8fc5edd:
      title: On Jetsün Drakpa Gyaltsen’s How to Take the Practice to Heart
      parent: Commentaries
    5a7d34918b744e6d900e442b42959c15:
      title: A Song to Aid the Recollection of Parental Kindness and Encourage the
        Recitation of the Maṇi Mantra
      parent: Compassion
    aca0154f592e4512b18e4044e4d1b2e2:
      title: A Song of Compassion
      parent: Compassion
    dfe1e85ab0284c53b07b2551e49a56a8:
      title: When Remembering My Mother
      parent: Compassion
    dce1234671a54c30971acb4c90d54b44:
      title: A Lamenting Plea for Compassion
      parent: Devotion
    6726429b1f75497b976bb2b33aad7469:
      title: A Song Recalling the Noble Guru’s Kindness
      parent: Devotion
    1a32cf735b784c1c81cedbba38aab95b:
      title: A Song Requested by the Buddhist Monk Jamyang Yönten Gyatso
      parent: Devotion
    98972124157944c98422e12ce5093a87:
      title: Lament Composed in a State of Deep Sadness
      parent: Devotion
    5a4f76f118a949c59ed71ccb23116966:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      parent: Devotion
    4ad5fd93a9ef4bea8560de0080c0af37:
      title: 'Piercing Devotion: A Lament for Lama Sakyapa'
      parent: Devotion
    333db4d12cb7419eb22217ceaafb1496:
      title: 'Tremendous Piercing of the Heart: A Lament Recalling the Guru'
      parent: Devotion
    720b8916152c4cd28dbc3e630e5e3e5e:
      title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great
        Guru of Oḍḍiyāna'
      parent: Devotion
    75a9e38fd9f14f7bba225b5c4337f9df:
      title: The Song of the Vajra
      parent: Dzogchen
    de7cc88e54834cc19cb3a86c80a4c4e2:
      title: A Song in Six Verses
      parent: Dzogchen
    cd8cbb252117423da35cba86bc6556e7:
      title: Song of Experiential Certainty
      parent: Dzogchen
    bba7de144dae4de6a786c0a879330498:
      title: Song that Arose Spontaneously at Taktse Podrang, Sikkim
      parent: Dzogchen
    14e9b3f01b4049b08d87e084a5487c43:
      title: Spontaneously Written Song of Experience
      parent: Dzogchen
    5ecbcfd895634ae09fd7fa22afd336a8:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    41ca049afaa54659b5b6f5681bc1ad38:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    cd166f21220c4d25b2b34cdec1a716bf:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    cb22aef793af4b9c97ad6bfb3414377c:
      title: In This Pure Awareness
      parent: Dzogchen
    0006287ff92c47ca897dca9b3a47b5b3:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Dzogchen
    2174b541fef8412ba55afc472f2680f4:
      title: Five-Verse Doha of Yogic Realization
      parent: Dzogchen
    6188391fda3e41cba0724f2c2926f6d0:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Dzogchen
    348d1d9eb4f241448bc048f561e7db72:
      title: Natural Great Peace
      parent: Dzogchen
    c03a8d3a3a934664ad79f195ef8de58f:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Feast Songs
    9281828bfb0348eba7df566b02e23d35:
      title: Song of the Feast (Tsok Lu)
      parent: Feast Songs
    76b55c2d670a4528b8b3bc3930e28199:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: General
    8664ca758658469187d9307f6a84250b:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: General
    aee99de859a04884b37ae982def3b655:
      title: A Short Song of Practice
      parent: General
    c43daf09d60748a087a7f02f33f28fa7:
      title: When Flowers Were Ravaged by the Frost
      parent: Impermanence
    418390a6945148ab883f1070187bf6e3:
      title: Verses of Advice for Meditating on Impermanence
      parent: Impermanence
    a695e676edf94f4c9278d251b1445724:
      title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
        and Fulfilment'
      parent: Joy
    2ef291b6b3e84d298e5429bb48e1a3d9:
      title: Drawing Out the Quintessence of the View
      parent: Lamdré
    95b15318d015481cb7dc6f63cae8566e:
      title: Song of Deathlessness
      parent: Longevity
    ceb74739d3794e54adca4f19be53ac58:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Mahāmudrā
    739f70dd4e854748ac2cb736ba81ed1e:
      title: 'Lightning Band of Faith: A Song to Invoke the Master’s Wisdom Mind'
      parent: Prayer
    b4d064fdba6244bdace0b822d6d7c20d:
      title: A Song of Prayer to Jamyang Loter Wangpo
      parent: Prayer
    a2f861f372704866881309c95facd9e2:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Sacred Places
    3c3c789babea49d8b3e6eec7806b7e0c:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    92701ed0219145f89631055c32cceb76:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    5d93968dc6ea499b97450b98fa7d6192:
      title: 'Great Stake to the Heart: A Song of Sadness'
      parent: Sadness
    8ea5b659bda543cd9671c96db1aa2973:
      title: Song of Prayer to Milarepa
      parent: Sadness
    9b2cddc345d04556b3c68df49abd975f:
      title: Twelve and a Half Crippled Verses
      parent: Wonder
created_at: '2022-03-01T05:55:44.205628'
last_modified_at: '2022-03-01T05:55:44.205631'
